version: "3.5"
services:
  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:${POSTGRESQL_VERSION}
    networks:
      - temporal-network
    expose:
      - 5432
    ports:
      - "${POSTGRES_DEFAULT_PORT:-5432}:5432"
    volumes:
      - /var/lib/postgresql/data
networks:
  temporal-network:
    driver: bridge
    name: temporal-network
  