---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  notify: restart fire2-worker

- name: restart fire2-worker
  ansible.builtin.systemd:
    name: fire2-worker
    state: restarted
