---
- name: reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  notify: restart fire2-worker instances

- name: restart fire2-worker instances
  ansible.builtin.systemd:
    name: "fire2-worker@{{ item }}"
    state: restarted
  loop: "{{ range(1, worker_instances + 1) | list }}"
