// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Build struct {
	ID        string    `json:"id"`
	Repo      string    `json:"repo"`
	Ref       string    `json:"ref"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Deployment struct {
	ID        string    `json:"id"`
	BuildID   string    `json:"build_id"`
	Status    string    `json:"status"`
	ImageTag  string    `json:"image_tag"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Port      string    `json:"port"`
}
