// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"
)

type Sandbox struct {
	ID         string    `json:"id"`
	Runtime    string    `json:"runtime"`
	Status     string    `json:"status"`
	Ttl        int64     `json:"ttl"`
	CreatedAt  time.Time `json:"created_at"`
	Port       int32     `json:"port"`
	PreviewUrl string    `json:"preview_url"`
	Image      string    `json:"image"`
}

type SandboxEvent struct {
	ID          string          `json:"id"`
	SandboxID   string          `json:"sandbox_id"`
	ContainerID string          `json:"container_id"`
	WorkerID    string          `json:"worker_id"`
	EventType   string          `json:"event_type"`
	Action      string          `json:"action"`
	ActorID     string          `json:"actor_id"`
	Attributes  json.RawMessage `json:"attributes"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

type Worker struct {
	ID            string    `json:"id"`
	Status        string    `json:"status"`
	Address       string    `json:"address"`
	Capacity      int32     `json:"capacity"`
	Port          int32     `json:"port"`
	CreatedAt     time.Time `json:"created_at"`
	CpuBudget     int32     `json:"cpu_budget"`
	MemBudget     int32     `json:"mem_budget"`
	CpuUsage      int32     `json:"cpu_usage"`
	MemUsage      int32     `json:"mem_usage"`
	LastHeartbeat time.Time `json:"last_heartbeat"`
}
