// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"encoding/json"
	"time"
)

type Sandbox struct {
	ID         string    `json:"id"`
	Runtime    string    `json:"runtime"`
	Status     string    `json:"status"`
	Ttl        int64     `json:"ttl"`
	CreatedAt  time.Time `json:"created_at"`
	Port       int32     `json:"port"`
	PreviewUrl string    `json:"preview_url"`
	Image      string    `json:"image"`
}

type Task struct {
	ID        string          `json:"id"`
	Payload   json.RawMessage `json:"payload"`
	Type      string          `json:"type"`
	SandboxID string          `json:"sandbox_id"`
	WorkerID  string          `json:"worker_id"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
}

type Worker struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	Address   string    `json:"address"`
	Capacity  int32     `json:"capacity"`
	Port      int32     `json:"port"`
	CreatedAt time.Time `json:"created_at"`
}
