// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"time"
)

const createBuild = `-- name: CreateBuild :one
INSERT INTO builds (id, repo, ref, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, repo, ref, status, created_at, updated_at
`

type CreateBuildParams struct {
	ID        string    `json:"id"`
	Repo      string    `json:"repo"`
	Ref       string    `json:"ref"`
	Status    string    `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, createBuild,
		arg.ID,
		arg.Repo,
		arg.Ref,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Ref,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeployment = `-- name: CreateDeployment :one
INSERT INTO deployments (id, build_id, status, image_tag, created_at, updated_at, port)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, build_id, status, image_tag, created_at, updated_at, port
`

type CreateDeploymentParams struct {
	ID        string    `json:"id"`
	BuildID   string    `json:"build_id"`
	Status    string    `json:"status"`
	ImageTag  string    `json:"image_tag"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
	Port      string    `json:"port"`
}

func (q *Queries) CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, createDeployment,
		arg.ID,
		arg.BuildID,
		arg.Status,
		arg.ImageTag,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Port,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Status,
		&i.ImageTag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Port,
	)
	return i, err
}

const getBuild = `-- name: GetBuild :one
SELECT id, repo, ref, status, created_at, updated_at FROM builds
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBuild(ctx context.Context, id string) (Build, error) {
	row := q.db.QueryRowContext(ctx, getBuild, id)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Ref,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeployment = `-- name: GetDeployment :one
SELECT id, build_id, status, image_tag, created_at, updated_at, port FROM deployments
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDeployment(ctx context.Context, id string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeployment, id)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Status,
		&i.ImageTag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Port,
	)
	return i, err
}

const getDeploymentByBuildID = `-- name: GetDeploymentByBuildID :one
SELECT id, build_id, status, image_tag, created_at, updated_at, port FROM deployments
WHERE build_id = $1 LIMIT 1
`

func (q *Queries) GetDeploymentByBuildID(ctx context.Context, buildID string) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentByBuildID, buildID)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Status,
		&i.ImageTag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Port,
	)
	return i, err
}

const listBuilds = `-- name: ListBuilds :many
SELECT id, repo, ref, status, created_at, updated_at FROM builds
ORDER BY created_at DESC
`

func (q *Queries) ListBuilds(ctx context.Context) ([]Build, error) {
	rows, err := q.db.QueryContext(ctx, listBuilds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Build
	for rows.Next() {
		var i Build
		if err := rows.Scan(
			&i.ID,
			&i.Repo,
			&i.Ref,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeployments = `-- name: ListDeployments :many
SELECT id, build_id, status, image_tag, created_at, updated_at, port FROM deployments
ORDER BY created_at DESC
`

func (q *Queries) ListDeployments(ctx context.Context) ([]Deployment, error) {
	rows, err := q.db.QueryContext(ctx, listDeployments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deployment
	for rows.Next() {
		var i Deployment
		if err := rows.Scan(
			&i.ID,
			&i.BuildID,
			&i.Status,
			&i.ImageTag,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Port,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBuild = `-- name: UpdateBuild :one
UPDATE builds
SET status = $2, updated_at = $3
WHERE id = $1
RETURNING id, repo, ref, status, created_at, updated_at
`

type UpdateBuildParams struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error) {
	row := q.db.QueryRowContext(ctx, updateBuild, arg.ID, arg.Status, arg.UpdatedAt)
	var i Build
	err := row.Scan(
		&i.ID,
		&i.Repo,
		&i.Ref,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDeployment = `-- name: UpdateDeployment :one
UPDATE deployments
SET status = $2, updated_at = $3, port = $4
WHERE id = $1
RETURNING id, build_id, status, image_tag, created_at, updated_at, port
`

type UpdateDeploymentParams struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	UpdatedAt time.Time `json:"updated_at"`
	Port      string    `json:"port"`
}

func (q *Queries) UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error) {
	row := q.db.QueryRowContext(ctx, updateDeployment,
		arg.ID,
		arg.Status,
		arg.UpdatedAt,
		arg.Port,
	)
	var i Deployment
	err := row.Scan(
		&i.ID,
		&i.BuildID,
		&i.Status,
		&i.ImageTag,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Port,
	)
	return i, err
}
