// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error)
	CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error)
	DeleteSandbox(ctx context.Context, id string) error
	DeleteWorker(ctx context.Context, id string) error
	GetSandbox(ctx context.Context, id string) (Sandbox, error)
	GetWorker(ctx context.Context, id string) (Worker, error)
	ListSandboxes(ctx context.Context) ([]Sandbox, error)
	ListWorkers(ctx context.Context) ([]Worker, error)
	UpdateSandbox(ctx context.Context, arg UpdateSandboxParams) (Sandbox, error)
	UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error)
}

var _ Querier = (*Queries)(nil)
