// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateBuild(ctx context.Context, arg CreateBuildParams) (Build, error)
	CreateDeployment(ctx context.Context, arg CreateDeploymentParams) (Deployment, error)
	GetBuild(ctx context.Context, id string) (Build, error)
	GetDeployment(ctx context.Context, id string) (Deployment, error)
	GetDeploymentByBuildID(ctx context.Context, buildID string) (Deployment, error)
	ListBuilds(ctx context.Context) ([]Build, error)
	ListDeployments(ctx context.Context) ([]Deployment, error)
	UpdateBuild(ctx context.Context, arg UpdateBuildParams) (Build, error)
	UpdateDeployment(ctx context.Context, arg UpdateDeploymentParams) (Deployment, error)
}

var _ Querier = (*Queries)(nil)
