// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sandbox_events.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createSandboxEvent = `-- name: CreateSandboxEvent :one
INSERT INTO sandbox_events (
    id,
    sandbox_id,
    container_id,
    worker_id,
    event_type,
    action,
    actor_id,
    attributes,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, sandbox_id, container_id, worker_id, event_type, action, actor_id, attributes, occurred_at
`

type CreateSandboxEventParams struct {
	ID          string          `json:"id"`
	SandboxID   string          `json:"sandbox_id"`
	ContainerID string          `json:"container_id"`
	WorkerID    string          `json:"worker_id"`
	EventType   string          `json:"event_type"`
	Action      string          `json:"action"`
	ActorID     string          `json:"actor_id"`
	Attributes  json.RawMessage `json:"attributes"`
	OccurredAt  time.Time       `json:"occurred_at"`
}

func (q *Queries) CreateSandboxEvent(ctx context.Context, arg CreateSandboxEventParams) (SandboxEvent, error) {
	row := q.db.QueryRowContext(ctx, createSandboxEvent,
		arg.ID,
		arg.SandboxID,
		arg.ContainerID,
		arg.WorkerID,
		arg.EventType,
		arg.Action,
		arg.ActorID,
		arg.Attributes,
		arg.OccurredAt,
	)
	var i SandboxEvent
	err := row.Scan(
		&i.ID,
		&i.SandboxID,
		&i.ContainerID,
		&i.WorkerID,
		&i.EventType,
		&i.Action,
		&i.ActorID,
		&i.Attributes,
		&i.OccurredAt,
	)
	return i, err
}
