// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sandbox_queries.sql

package db

import (
	"context"
	"time"
)

const createSandbox = `-- name: CreateSandbox :one
INSERT INTO sandboxes (id,  runtime, status, image, port, ttl, preview_url, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, runtime, status, ttl, created_at, port, preview_url, image
`

type CreateSandboxParams struct {
	ID         string    `json:"id"`
	Runtime    string    `json:"runtime"`
	Status     string    `json:"status"`
	Image      string    `json:"image"`
	Port       int32     `json:"port"`
	Ttl        int64     `json:"ttl"`
	PreviewUrl string    `json:"preview_url"`
	CreatedAt  time.Time `json:"created_at"`
}

func (q *Queries) CreateSandbox(ctx context.Context, arg CreateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, createSandbox,
		arg.ID,
		arg.Runtime,
		arg.Status,
		arg.Image,
		arg.Port,
		arg.Ttl,
		arg.PreviewUrl,
		arg.CreatedAt,
	)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.Runtime,
		&i.Status,
		&i.Ttl,
		&i.CreatedAt,
		&i.Port,
		&i.PreviewUrl,
		&i.Image,
	)
	return i, err
}

const deleteSandbox = `-- name: DeleteSandbox :exec
DELETE FROM sandboxes
WHERE id = $1
`

func (q *Queries) DeleteSandbox(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSandbox, id)
	return err
}

const getSandbox = `-- name: GetSandbox :one
SELECT id, runtime, status, ttl, created_at, port, preview_url, image FROM sandboxes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSandbox(ctx context.Context, id string) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, getSandbox, id)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.Runtime,
		&i.Status,
		&i.Ttl,
		&i.CreatedAt,
		&i.Port,
		&i.PreviewUrl,
		&i.Image,
	)
	return i, err
}

const listSandboxes = `-- name: ListSandboxes :many
SELECT id, runtime, status, ttl, created_at, port, preview_url, image FROM sandboxes
ORDER BY id DESC
`

func (q *Queries) ListSandboxes(ctx context.Context) ([]Sandbox, error) {
	rows, err := q.db.QueryContext(ctx, listSandboxes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sandbox
	for rows.Next() {
		var i Sandbox
		if err := rows.Scan(
			&i.ID,
			&i.Runtime,
			&i.Status,
			&i.Ttl,
			&i.CreatedAt,
			&i.Port,
			&i.PreviewUrl,
			&i.Image,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSandbox = `-- name: UpdateSandbox :one
UPDATE sandboxes
SET status = $2
WHERE id = $1
RETURNING id, runtime, status, ttl, created_at, port, preview_url, image
`

type UpdateSandboxParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSandbox(ctx context.Context, arg UpdateSandboxParams) (Sandbox, error) {
	row := q.db.QueryRowContext(ctx, updateSandbox, arg.ID, arg.Status)
	var i Sandbox
	err := row.Scan(
		&i.ID,
		&i.Runtime,
		&i.Status,
		&i.Ttl,
		&i.CreatedAt,
		&i.Port,
		&i.PreviewUrl,
		&i.Image,
	)
	return i, err
}
