// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: task_queries.sql

package db

import (
	"context"
	"encoding/json"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO task (id, payload, type, sandbox_id, worker_id, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6,$7)
RETURNING id, payload, type, sandbox_id, worker_id, status, created_at
`

type CreateTaskParams struct {
	ID        string          `json:"id"`
	Payload   json.RawMessage `json:"payload"`
	Type      string          `json:"type"`
	SandboxID string          `json:"sandbox_id"`
	WorkerID  string          `json:"worker_id"`
	Status    string          `json:"status"`
	CreatedAt time.Time       `json:"created_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.Payload,
		arg.Type,
		arg.SandboxID,
		arg.WorkerID,
		arg.Status,
		arg.CreatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Type,
		&i.SandboxID,
		&i.WorkerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, payload, type, sandbox_id, worker_id, status, created_at FROM task
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Type,
		&i.SandboxID,
		&i.WorkerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listTasksBySandboxID = `-- name: ListTasksBySandboxID :many
SELECT id, payload, type, sandbox_id, worker_id, status, created_at FROM task
WHERE sandbox_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListTasksBySandboxID(ctx context.Context, sandboxID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksBySandboxID, sandboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Payload,
			&i.Type,
			&i.SandboxID,
			&i.WorkerID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE task
SET status = $2
WHERE id = $1
RETURNING id, payload, type, sandbox_id, worker_id, status, created_at
`

type UpdateTaskStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Payload,
		&i.Type,
		&i.SandboxID,
		&i.WorkerID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
