// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker_queries.sql

package db

import (
	"context"
	"time"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (id, status, address, Capacity, port, cpu_budget, mem_budget, cpu_usage, mem_usage, last_heartbeat, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, status, address, capacity, port, created_at, cpu_budget, mem_budget, cpu_usage, mem_usage, last_heartbeat
`

type CreateWorkerParams struct {
	ID            string    `json:"id"`
	Status        string    `json:"status"`
	Address       string    `json:"address"`
	Capacity      int32     `json:"capacity"`
	Port          int32     `json:"port"`
	CpuBudget     int32     `json:"cpu_budget"`
	MemBudget     int32     `json:"mem_budget"`
	CpuUsage      int32     `json:"cpu_usage"`
	MemUsage      int32     `json:"mem_usage"`
	LastHeartbeat time.Time `json:"last_heartbeat"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.ID,
		arg.Status,
		arg.Address,
		arg.Capacity,
		arg.Port,
		arg.CpuBudget,
		arg.MemBudget,
		arg.CpuUsage,
		arg.MemUsage,
		arg.LastHeartbeat,
		arg.CreatedAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
		&i.CpuBudget,
		&i.MemBudget,
		&i.CpuUsage,
		&i.MemUsage,
		&i.LastHeartbeat,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM worker
WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, id)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, status, address, capacity, port, created_at, cpu_budget, mem_budget, cpu_usage, mem_usage, last_heartbeat FROM worker
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorker(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
		&i.CpuBudget,
		&i.MemBudget,
		&i.CpuUsage,
		&i.MemUsage,
		&i.LastHeartbeat,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, status, address, capacity, port, created_at, cpu_budget, mem_budget, cpu_usage, mem_usage, last_heartbeat FROM worker
ORDER BY id DESC
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Address,
			&i.Capacity,
			&i.Port,
			&i.CreatedAt,
			&i.CpuBudget,
			&i.MemBudget,
			&i.CpuUsage,
			&i.MemUsage,
			&i.LastHeartbeat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE worker
SET status = $2, address = $3, Capacity = $4, port = $5, cpu_budget = $6, mem_budget = $7, cpu_usage = $8, mem_usage = $9, last_heartbeat = $10
WHERE id = $1
RETURNING id, status, address, capacity, port, created_at, cpu_budget, mem_budget, cpu_usage, mem_usage, last_heartbeat
`

type UpdateWorkerParams struct {
	ID            string    `json:"id"`
	Status        string    `json:"status"`
	Address       string    `json:"address"`
	Capacity      int32     `json:"capacity"`
	Port          int32     `json:"port"`
	CpuBudget     int32     `json:"cpu_budget"`
	MemBudget     int32     `json:"mem_budget"`
	CpuUsage      int32     `json:"cpu_usage"`
	MemUsage      int32     `json:"mem_usage"`
	LastHeartbeat time.Time `json:"last_heartbeat"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, updateWorker,
		arg.ID,
		arg.Status,
		arg.Address,
		arg.Capacity,
		arg.Port,
		arg.CpuBudget,
		arg.MemBudget,
		arg.CpuUsage,
		arg.MemUsage,
		arg.LastHeartbeat,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
		&i.CpuBudget,
		&i.MemBudget,
		&i.CpuUsage,
		&i.MemUsage,
		&i.LastHeartbeat,
	)
	return i, err
}
