// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: worker_queries.sql

package db

import (
	"context"
	"time"
)

const createWorker = `-- name: CreateWorker :one
INSERT INTO worker (id, status, address, Capacity, port, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, status, address, capacity, port, created_at
`

type CreateWorkerParams struct {
	ID        string    `json:"id"`
	Status    string    `json:"status"`
	Address   string    `json:"address"`
	Capacity  int32     `json:"capacity"`
	Port      int32     `json:"port"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateWorker(ctx context.Context, arg CreateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, createWorker,
		arg.ID,
		arg.Status,
		arg.Address,
		arg.Capacity,
		arg.Port,
		arg.CreatedAt,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWorker = `-- name: DeleteWorker :exec
DELETE FROM worker
WHERE id = $1
`

func (q *Queries) DeleteWorker(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWorker, id)
	return err
}

const getWorker = `-- name: GetWorker :one
SELECT id, status, address, capacity, port, created_at FROM worker
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetWorker(ctx context.Context, id string) (Worker, error) {
	row := q.db.QueryRowContext(ctx, getWorker, id)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
	)
	return i, err
}

const listWorkers = `-- name: ListWorkers :many
SELECT id, status, address, capacity, port, created_at FROM worker
ORDER BY id DESC
`

func (q *Queries) ListWorkers(ctx context.Context) ([]Worker, error) {
	rows, err := q.db.QueryContext(ctx, listWorkers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Worker
	for rows.Next() {
		var i Worker
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Address,
			&i.Capacity,
			&i.Port,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorker = `-- name: UpdateWorker :one
UPDATE worker
SET status = $2, address = $3, Capacity = $4, port = $5
WHERE id = $1
RETURNING id, status, address, capacity, port, created_at
`

type UpdateWorkerParams struct {
	ID       string `json:"id"`
	Status   string `json:"status"`
	Address  string `json:"address"`
	Capacity int32  `json:"capacity"`
	Port     int32  `json:"port"`
}

func (q *Queries) UpdateWorker(ctx context.Context, arg UpdateWorkerParams) (Worker, error) {
	row := q.db.QueryRowContext(ctx, updateWorker,
		arg.ID,
		arg.Status,
		arg.Address,
		arg.Capacity,
		arg.Port,
	)
	var i Worker
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Address,
		&i.Capacity,
		&i.Port,
		&i.CreatedAt,
	)
	return i, err
}
